const PrivacyPolicy = () => {
  return (
    <div className="section-padding">
      <div className="container-wide max-w-3xl mx-auto">
        <h1 className="font-heading text-4xl font-bold text-foreground uppercase mb-2">Privacy Policy</h1>
        <p className="text-primary font-heading font-semibold mb-8">SplendorUAE</p>

        <div className="prose prose-sm max-w-none text-muted-foreground space-y-4">
          <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You respond to our advertisements and tells You about Your privacy rights and how the law protects You. We use Your Personal Data to contact and support you, as well as to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>

          <h2 className="font-heading text-xl font-bold text-foreground mt-8">Interpretation and Definitions</h2>
          <h3 className="font-heading text-lg font-bold text-foreground mt-6">Interpretation</h3>
          <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

          <h3 className="font-heading text-lg font-bold text-foreground mt-6">Definitions</h3>
          <p>For the purposes of this Privacy Policy:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li><strong className="text-foreground">Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to SplendorUAE.</li>
            <li><strong className="text-foreground">Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
            <li><strong className="text-foreground">Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
            <li><strong className="text-foreground">Service</strong> refers to the advertisement, website, or application.</li>
            <li><strong className="text-foreground">Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
            <li><strong className="text-foreground">Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
            <li><strong className="text-foreground">You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
          </ul>

          <h2 className="font-heading text-xl font-bold text-foreground mt-8">Collecting and Using Your Personal Data</h2>
          <h3 className="font-heading text-lg font-bold text-foreground mt-6">Types of Data Collected</h3>
          <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>First and last name</li>
            <li>Email address</li>
            <li>Phone number</li>
            <li>Location details such as your address, city or country</li>
            <li>Any other data such as personal preferences, requirements or comments</li>
          </ul>

          <h3 className="font-heading text-lg font-bold text-foreground mt-6">Use of Your Personal Data</h3>
          <p>The Company may use Personal Data for the following purposes:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
            <li>To manage Your Account: to manage Your registration as a user of the Service.</li>
            <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased.</li>
            <li>To contact You: by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
            <li>To provide You with news, special offers and general information about other goods, services and events which we offer.</li>
            <li>To manage Your requests: To attend and manage Your requests to Us.</li>
            <li>For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
            <li>For other purposes: such as data analysis, identifying usage trends, and to evaluate and improve our Service.</li>
          </ul>

          <p className="mt-4">We may share Your personal information in the following situations:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li><strong className="text-foreground">With Service Providers:</strong> We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</li>
            <li><strong className="text-foreground">For business transfers:</strong> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition.</li>
            <li><strong className="text-foreground">With Your consent:</strong> We may disclose Your personal information for any other purpose with Your consent.</li>
          </ul>

          <h2 className="font-heading text-xl font-bold text-foreground mt-8">Retention of Your Personal Data</h2>
          <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.</p>

          <h2 className="font-heading text-xl font-bold text-foreground mt-8">Transfer of Your Personal Data</h2>
          <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>

          <h2 className="font-heading text-xl font-bold text-foreground mt-8">Disclosure of Your Personal Data</h2>
          <h3 className="font-heading text-lg font-bold text-foreground mt-6">Law enforcement</h3>
          <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities.</p>
          <h3 className="font-heading text-lg font-bold text-foreground mt-6">Other legal requirements</h3>
          <p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Comply with a legal obligation</li>
            <li>Protect and defend the rights or property of the Company</li>
            <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
            <li>Protect the personal safety of Users of the Service or the public</li>
            <li>Protect against legal liability</li>
          </ul>

          <h2 className="font-heading text-xl font-bold text-foreground mt-8">Security of Your Personal Data</h2>
          <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>

          <h2 className="font-heading text-xl font-bold text-foreground mt-8">Links to Other Websites</h2>
          <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>

          <h2 className="font-heading text-xl font-bold text-foreground mt-8">Changes to this Privacy Policy</h2>
          <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
          <p>This Privacy Policy was last updated on 2024/04/03.</p>

          <h2 className="font-heading text-xl font-bold text-foreground mt-8">Contact Us</h2>
          <p>If you have any questions about this Privacy Policy, You can contact us via email at <a href="mailto:info@splendoruae.com" className="text-primary hover:underline">info@splendoruae.com</a>.</p>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
